// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fplnoozuxxqbjkrvvwxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbG5vb3p1eHhxYmprcnZ2d3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODM0MzQsImV4cCI6MjA2MDA1OTQzNH0.WCbtjNQLsZOd9zblfAUl2EC2L4uthqEdv8mre6aKgc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);